### PR TITLE
Add color when creating post

### PR DESCRIPTION
**Pull request by victorteokw**
See #5

### CODE REVIEW

**Comment by cheunghy** [comment]
This commit contains several small bugs:

1. when deletion, textarea will shift above a little bit.
2. when delete to the box is empty, the cursor becomes very big.

But it totally works.

I will fix the two small issue in the future.

**Comment by cheunghy** [comment]
Don't merge it yet. It breaks emoticon.

**Comment by cheunghy** [comment]
Does version 0.0.6 fix for you?

**Comment by cuterxy** [comment]
Great! I will check it later.

**Comment by cheunghy** [comment]
I will fix the emoticon issue before you merge.

**Pull request closed without merging**
